Fix crash issue on winning a game
mPersistStatsAsyncTask was being run twice in cases where you won a game, which causes a crash (below). Switching to a separate HandlerThread and posting a Runnable prevents this from being a problem and ensures that each persist call is done sequentially.

java.lang.IllegalStateException: Cannot execute task: the task has already been executed (a task can be executed only once)
at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:579)
at android.os.AsyncTask.execute(AsyncTask.java:535)
at com.github.triplesolitaire.TripleSolitaireActivity.a(SourceFile:458)
at com.github.triplesolitaire.TripleSolitaireActivity.a(SourceFile:61)
at com.google.android.gms.common.api.l.b(Unknown Source)
at com.google.android.gms.common.api.l.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)